version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 657103446220.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t savi-api .
      - docker tag savi-api:latest 657103446220.dkr.ecr.us-east-1.amazonaws.com/savi-api:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 657103446220.dkr.ecr.us-east-1.amazonaws.com/savi-api:latest
